export const cartConstants = {
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "ADD_PRODUCT_FROM_CART",
  ADD_ITEM_PRODUCT: "ADD_ITEM_PRODUCT",
  SUBSTRACT_ITEM_PRODUCT: "SUBSTRACT_ITEM_PRODUCT"
};
