export const catalogConstants = {
  ADD_PRODUCT: "ADD_PRODUCT_TO_CATALOG",
  FETCH_SEARCH_DATA: "FETCH_SEARCH_DATA",
  FETCH_SEARCH_SUCCESS: "FETCH_SEARCH_SUCCESS",
  FETCH_SEARCH_FAILURE: "FETCH_SEARCH_FAILURE"
};
