export const productConstants = {
  ADD_PRODUCT: "USERS_LOGIN_REQUEST",
  FETCH_SEARCH_DATA: "FETCH_SEARCH_DATA",
  FETCH_SEARCH_SUCCESS: "FETCH_SEARCH_SUCCESS",
  FETCH_SEARCH_FAILURE: "FETCH_SEARCH_FAILURE"
};
